[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
]

[fmt]
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
